# Generated by Django 4.2.2 on 2023-06-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristics', models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Science'), ('5', 'Mathematics'), ('6', 'History'), ('7', 'Geography'), ('8', 'Literature'), ('9', 'Physics'), ('10', 'Chemistry'), ('11', 'Biology'), ('12', 'Computer Science'), ('13', 'Art'), ('14', 'Music'), ('15', 'Sports')], default='1', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='quizset',
            name='caracteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.caracteristics'),
        ),
    ]
