# Generated by Django 4.2.2 on 2023-07-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_quizset_caracteristics_quizset_caracteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristics',
            name='caracteristics',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Science'), ('5', 'Mathematics'), ('6', 'History'), ('7', 'Geography'), ('8', 'Literature'), ('9', 'Physics'), ('10', 'Chemistry'), ('11', 'Biology'), ('12', 'Computer Science'), ('13', 'Art'), ('14', 'Music'), ('15', 'Sports'), ('16', 'Networking'), ('15', 'Database')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
