# Generated by Django 4.2.2 on 2023-07-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_caracteristics_caracteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
