# Generated by Django 4.2.2 on 2023-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_quizset_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristics',
            name='caracteristics',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Science'), ('5', 'Mathematics'), ('6', 'History'), ('7', 'Geography'), ('8', 'Literature'), ('9', 'Physics'), ('10', 'Chemistry'), ('11', 'Biology'), ('12', 'Computer Science'), ('13', 'Art'), ('14', 'Music'), ('15', 'Sports'), ('16', 'Networking'), ('15', 'Database'), ('17', 'Front End'), ('18', 'Back End'), ('19', 'Full Stack'), ('20', 'Web Development'), ('21', 'Mobile Development'), ('22', 'Database'), ('23', 'API'), ('24', 'Open Source'), ('25', 'Security'), ('26', 'DevOps'), ('27', 'System Design'), ('28', 'Algorithms'), ('29', 'Data Structures'), ('30', 'Software Design'), ('31', 'Software Engineering'), ('32', 'Version Control'), ('33', 'Testing'), ('34', 'Debugging'), ('35', 'Cloud'), ('36', 'Programming Languages'), ('37', 'Problem Solving'), ('38', 'Game Development'), ('39', 'UI/UX'), ('40', 'Software Architecture'), ('17', 'JavaScript'), ('181', 'Python'), ('191', 'Java'), ('201', 'C++'), ('211', 'PHP'), ('221', 'HTML'), ('231', 'CSS'), ('241', 'SQL'), ('251', 'Ruby'), ('261', 'C#'), ('271', 'C'), ('281', 'React'), ('291', 'Angular'), ('301', 'jQuery'), ('311', 'Android'), ('321', 'iOS'), ('331', 'Swift'), ('341', 'Node.js'), ('351', 'ASP.NET'), ('361', 'Linux'), ('371', 'Shell'), ('381', 'Algorithms'), ('391', 'Data structures'), ('401', 'Programming fundamentals')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='exams',
            field=models.ManyToManyField(blank=True, null=True, to='listings.exam'),
        ),
    ]
