# Generated by Django 4.2.2 on 2023-07-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_userquizprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizprogress',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.question'),
        ),
    ]
