# Generated by Django 4.2.2 on 2023-07-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_userquizprogress_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
