# Generated by Django 4.2.2 on 2023-07-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_userquizprogress_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='questions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
